{% set name = "tyssue" %}
{% set version = "0.3.0.rc1" %}
{% set sha256 = "cc4fed073b3ed1a568184dca2ca064e6e01d88b5087199220230c3264aaf14a2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 1002
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k or py35]
requirements:
  host:
    - python
    - setuptools
    - cgal
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: GPLv3.0
  license_file: LICENSE
  summary: 'A tissue simulation library'
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
