{% set name = "tyssue" %}
{% set version = "0.3.rc4" %}
{% set sha256 = "58043df3d10818c23ae35f7a1288f48474ec99248a09683c06aa9a7920f57ce8" %}
{% set cgal_version = "4.13" %}
{% set cgal_sha256 = "c4912a00e99f29ee37cac1d780d115a048743370b9329a2cca839ffb392f3516" %}
{% set pb11_version = "2.2.4" %}
{% set pb11_sha256 = "b69e83658513215b8d1443544d0549b7d231b9f201f6fc787a2b2218b408181e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - fn: pybind11-{{ pb11_version }}.tar.gz
    url: https://github.com/pybind/pybind11/archive/v{{ pb11_version }}.tar.gz
    folder: pybind11
    sha256: {{ pb11_sha256 }}
  - url: https://github.com/CGAL/cgal/archive/releases/CGAL-{{ cgal_version }}.tar.gz
    folder: CGAL
    sha256: {{ cgal_sha256 }}


build:
  number: 0
  skip: True  # [py2k or py35]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - eigen
    - boost-cpp
    - mpfr
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: GPLv3.0
  license_file: LICENSE
  summary: 'A tissue simulation library'
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
