{% set name = "tyssue" %}
{% set version = "1.0.1" %}
{% set sha256 = "e51c64553527f8dbcb81b8a0878757620d1dd9bb34f9db78fead4a1a5651f242" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [py2k or py35]
  skip: true  # [win and vc<14]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - mpfr
    - cgal
    - jom  # [win]
    - setuptools-scm
    - scikit-build-core

  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - boost-cpp
    - mpfr
    - gmp
    - cgal
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipython
    - ipython_genutils
    - ipywidgets
    - pythreejs
    - ipyvolume
    - vispy
    - meshio
    - zarr
    - xarray
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A tissue simulation library
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.10+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
