{% set name = "tyssue" %}
{% set version = "1.0.pre" %}
{% set sha256 = "402e5deb696e4574f77e219b9625a3ae6e277aca25a8c21596be21f759773de5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - mpfr
    - cgal
    - jom  # [win]
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
    - vispy
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A tissue simulation library
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
