{% set name = "tyssue" %}
{% set version = "0.2.3" %}
{% set sha256 = "0c3068ec257ce2018e24f26e4fc4b810a02fcf819857edbdb19e855547e4a203" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k or py35]
requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: MPLv2.0
  license_file: LICENSE
  summary: 'A tissue simulation library'
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
