{% set name = "tyssue" %}
{% set version = "0.7.0" %}
{% set sha256 = "78afecb875abdde9f8fb4b499d6eb0433c852509bb5559c17bdc32abd4207ce9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - fn: pybind11-2.4.3.tar.gz
    url: https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz
    folder: pybind11
    sha256: 1eed57bc6863190e35637290f97a20c81cfe4d9090ac0a24f3bbf08f265eb71d
  - url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-5.0/CGAL-5.0.zip
    folder: CGAL
    sha256: bd9327be903ab7ee379a8a7a0609eba0962f5078d2497cf8e13e8e1598584154

build:
  number: 4
  skip: true  # [py2k or py35]
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - eigen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost-cpp
    - mpfr
    - jom  # [win]
  host:
    - python
    - setuptools
    - pip
  run:
    - boost-cpp
    - mpfr
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license:  GPL-3.0-or-later
  license_file: LICENSE
  summary: 'A tissue simulation library'
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
