appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: v8r+xbTSHeErmUIdzZ2kICrx7kM1ZRikasefev9Ccdies/pLQYovJGmJb6OP2ZEzKPG19vf1gRpXOwRys2TmCrzFSZ+7Q/rikeYEMufpHa4l3v3Eu3JwLSdFpDWV5IpypQkkFf7ljjzkcDdVE+JSEvH/phsQHMY73UnLRPfNYQqP3KBac7Td3tqCisynyXgZW00bo2R3RPtM+3fpbkFfb7TKGo4ttwnp1jusm5+CS+fBHWi+NmZHNAWHc5AmiMph5BcycdmgDH63id4sWKRh6DVJf1G7ra5R8nlF2lL8YgSFFkYfnYch1iqp9V3BA7e1w5IVwnD51qstyh4/4f1eyIpl8i8jYWn8ys6cxnCOKYxJFTZtsCh+18owUzffT5sdRXiltUP8z3juP8q86h+XQMk+NtZSQWamWYDwqjIsA06V0GLZWC0SQvkQtlK3HP0DwLyNd3dLZvqpjvoiXPwNjxpDAbtK8RsgX/D+QWjYholxrOBuXaurwfNzJbddoqmGhTaXQ0Ln8sitSRlIxaLvUNN6zRccqCKfSzd9X0ciQKt7/x2K4i2j1bS4XXExHgGAw258bpNuBRsuZrcTSnBrh5ns8hxy3LcjH7NdLchZm+TTxczUglCiTHmcHa1aznYTksyLTDmd6W7Bzp2+m+do/9jSjfCapnZWOrw9XHZnFw8=}
provider:
  win: azure
conda_forge_output_validation: true
